config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("web.urls")),
]

web/urls.py
"""webのURLパターン定義"""
from django.urls import path
from .applications import decks, skills, views

app_name = "web"
urlpatterns = [
    path("", views.index, name="index"),
    path('register/deck', decks.register_deck, name='register_deck'),
    path('delete/deck', decks.delete_deck, name='delete_deck'),
    path('skills', views.select_skills, name='select_skills'),
    path('register/skill', skills.register_skill, name='register_skill'),
    path('delete/skill', skills.delete_skill, name='delete_skill'),
]

web/templates/web/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" class="h-100">
<head>
    <meta charset="UTF-8">
    <title>Pokemon_tool</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">
    <link href="{% static 'css/pokemon_box.css' %}" rel="stylesheet">
    <style type="text/css">
    header{
      height: 50px;
      box-shadow: 0px 0px 5px 0px hsla(0, 0%, 7%, 0.3);
    }
    nav {
      width: 230px;
    }
    .nav-link {
        color: white;
        background-color: rgba(255, 255, 255, 0.493);
    }
    </style>
</head>
<body class="h-100">
<header class="w-100 d-flex justify-content-between align-items-center bg-light px-3">
    <ul class="navbar-nav d-flex flex-row">
        <li class="nav-item mx-3 text-muted active"><a href="#" class="nav-link text-secondary">New</a></li>
        <li class="nav-item mx-3 text-muted"><a href="#" class="nav-link text-secondary">Login</a></li>
    </ul>
</header>
<div class="d-flex flex-row w-100" style="height: calc(100% - 50px)">
        <nav class ="bg-dark">
            <ul class="nav flex-column m-0 p-3">
                <li class="nav-item mb-2"><a href="/?deck_id=1" class="nav-link">Deck1</a></li>
                <li class="nav-item mb-2"><a href="/?deck_id=2" class="nav-link">Deck2</a></li>
                <li class="nav-item mb-2"><a href="/?deck_id=3" class="nav-link">Deck3</a></li>
            </ul>
        </nav>
    <main class="w-100 bg-light overflow-auto">
        {% block content %}{% endblock content %}
    </main>
</div>
</body>
</html>

web/templates/web/error.html
{% extends "web/base.html" %}
{% block content %}
<p>不正エラーです</p>
{% endblock content %}

web/templates/web/no_deck.html
{% extends "web/base.html" %}
{% block content %}
<p>deckが選択されていません</p>
{% endblock content %}

web/templates/web/search.html
{% extends "web/base.html" %}
{% block content %}
<div class="p-3">
{% if msg %}
<div class="alert alert-danger" role="alert">{{msg}}</div>
{% endif %}
    <div class="d-flex flex-row">
        <div class="container">
            <div class="row">
                <div class="col-2">
                    <b>弱点をつけないタイプ: </b>
                </div>
                <div class="col-10">
                    {% for weakness_type in type_compatibility %}
                    <span class="type_color_{{weakness_type.id}} type_icon"> {{weakness_type.name}} </span>
                    {% endfor %}
                </div>
            </div>
            <div class="row justify-content-md-center">
                <div class="col-6">
                    {% if deck_pokemons|length > 0 %}
                    {% for deck_pokemon in deck_pokemons %}
                    <div class="row justify-content-md-center border-bottom border-1">
                        <div class="col-3 d-flex text-left align-items-center">
                            <a href="/skills?deck_set_id={{deck_pokemon.deck_set_id}}" style="color:inherit;text-decoration:none;"><i class="bi bi-pen"></i></a>
                            <form method="POST" action="{% url 'web:delete_deck' %}" style="z-index:99;">
                                {% csrf_token %}
                                <input type="hidden" name="criteria" value="{{criteria}}">
                                <input type="hidden" name="deck_set_id" value="{{deck_pokemon.deck_set_id}}">
                                <input type="hidden" name="deck_id" value="{{deck_id}}">
                                <button class="btn btn-default" type="submit">
                                    <i class="bi bi-trash3" role="img" aria-label="delete"></i>
                                </button>
                            </form>
                            <img src="{{deck_pokemon.pokemon_view.icon}}" style="width:65px;" alt="img" class="card-img-top">
                        </div>
                    <div class="col-2 d-flex align-items-center text-center">
                        <b>{{deck_pokemon.pokemon_view.name}}</b>
                    </div>
                        <div class="col-2 d-flex align-items-center text-center">
                            <span class="type_color_{{deck_pokemon.pokemon_view.type1_id}} type_icon"> {{deck_pokemon.pokemon_view.type1_name}} </span>
                            <span class="type_color_{{deck_pokemon.pokemon_view.type2_id}} type_icon ">{{deck_pokemon.pokemon_view.type2_name}} </span>
                        </div>
                        <div class="col-4 text-left ">
                            {% for skill_view in deck_pokemon.skill_views %}
                            <div class="row mt-0 d-flex align-items-center">
                                <div class="col-9">
                                    {{skill_view.name}}
                                </div>
                                <div class="col-3">
                                    <span class="type_color_{{skill_view.type_id}} type_icon"> {{skill_view.type_name}} </span>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                    {% endfor %}
                    {% else %}
                    <p>No hit</p>
                    {% endif %}
                </div>
                <div class="col-6">
                    <form method="get" action="/">

                        <div>
                            <p>ポケモンの名前を入力してください。</p>
                            <input type="hidden" name="deck_id" value="{{deck_id}}">
                            <input type="text" name="criteria" placeholder="キーワードを入力" value="{{criteria}}">
                            <input type="submit" value="検索">
                        </div>
                    </form>
                    <p>ポケモン検索結果</p>
                    {% if pokemon_views|length > 0 %}
                    <div class="overflow-auto" style="height:80vh;">
                        {% for pokemon_view in pokemon_views %}
                        <div class="polaroid ">
                            <form method="POST" action="{% url 'web:register_deck' %}">
                                {% csrf_token %}
                                <input type="hidden" name="criteria" value="{{criteria}}">
                                <input type="hidden" name="deck_id" value="{{deck_id}}">
                                <input type="hidden" name="pokemon_id" value="{{pokemon_view.id}}">
                                <button class="btn btn-default" type="submit">
                                    <i class="bi bi-patch-plus" role="img" aria-label="plus"></i>
                                </button>
                            </form>
                            <span class="masking-tape">No.{{pokemon_view.id}}</span>
                            <img src="{{pokemon_view.icon}}" alt="{{pokemon_view.name}}">
                            <div class="pokemon-profile">
                                <p class="polaroid-caption">{{pokemon_view.name}}
                                    <span class="type_color_{{pokemon_view.type1_id}} type_icon">
                                        {{pokemon_view.type1_name}}
                                    </span>
                                    <span class="type_color_{{pokemon_view.type2_id}} type_icon ">
                                        {{pokemon_view.type2_name}}
                                    </span>
                                </p>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    {% else %}
                    <p>No hit</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

web/templates/web/skills.html
{% extends "web/base.html" %}
{% block content %}
{% if msg %}
    <div class="alert alert-danger" role="alert">{{msg}}</div>
{% endif %}
<a href="/?deck_id={{deck_pokemon.deck_id}}">戻る</a>
<div class="container">
  <div style="background-color:#FFFFF0;">
  <h4 class="card-title text-center">{{deck_pokemon.pokemon_view.name}}</h4>
  <div class="row justify-content-md-center">
    <div class="col-md-auto">
      <img src="{{deck_pokemon.pokemon_view.icon}}" alt="img" class="card-img-top">
    </div>
  </div>
  <div class="row justify-content-md-center">
    {% for skill_view in deck_pokemon.skill_views %}
    <div class="col-md-auto border border-2 rounded">
      <form method="POST" action="{% url 'web:delete_skill' %}" >
        {% csrf_token %}
        <input type="hidden" name="deck_set_id" value="{{deck_pokemon.deck_set_id}}">
        <input type="hidden" name="skill_id" value="{{skill_view.id}}">
        {{skill_view.name}} <span class="type_color_{{skill_view.type_id}} type_icon"> {{skill_view.type_name}} </span>
          <button class="btn btn-default" type="submit">
            <i class="bi bi-patch-minus" role="img" aria-label="delete"></i>
          </button>
      </form>
    </div>
    {% endfor %}
  </div>
  </div>
  <hr>
  <h4 class="card-title text-center">技一覧</h4>
  <div class="row justify-content-md-center">
    {% for skill in skills %}
    <div class="col-2 border-bottom border-start border-top border-1">
      <form method="POST" action="{% url 'web:register_skill' %}" >
        {% csrf_token %}
        <input type="hidden" name="criteria" value="{{criteria}}">
        <input type="hidden" name="deck_set_id" value="{{deck_pokemon.deck_set_id}}">
        <input type="hidden" name="skill_id" value="{{skill.id}}">
        <button class="btn btn-default" type="submit">
          <i class="bi bi-patch-plus" role="img" aria-label="plus"></i>
        </button> {{ skill.name }}
      </form>
    </div>
      <div class="col-1 border-bottom border-end border-top border-1">
          <span class="type_color_{{skill.type_id}} type_icon">{{skill.type_name}}</span>
      </div>
    {% endfor %}
  </div>
</div>
{% endblock content %}